# Generated by Django 4.2.16 on 2024-09-23 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_measure_unit_ingredient_measurement_unit_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourites',
            field=models.ManyToManyField(related_name='lovers', to='recipes.recipe', verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='+', to='recipes.recipe', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
