# Generated by Django 4.2.16 on 2024-10-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('is_staff', '-date_joined'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
